version: "3.9"

services:
    app:
        build: .
        container_name: node_pfo2
        ports:
            - "3000:3000"
        environment:
            - MONGO_URL=mongodb://mongo:27017/escuela
        depends_on:
            - mongo
       

    mongo:
        image: mongo:7
        container_name: mongo_pfo2
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
